### ISSUE TITLE
doc doesn't tell how to run it

### ISSUE THREAD

**Issue by jrlandau** [UbiquityRobotics/demos#2]

**Comment by rohbotics** [comment]
Was is "it" ? Fiducial follow or partybot?

**Comment by jrlandau** [comment]
I guess I should have said "them".  But I was primarily concerned with
fiducial follow.

Actually I do not know whether partybot is part of the product.
@davidcrawley, is it?

**Comment by rohbotics** [comment]
Closing because the fiducial follow readme has documentation, and partybot is not in a working state
