### ISSUE TITLE
FloorFollow will require changes to Sonar Board and URDF for better up in front avoidance

### ISSUE THREAD

**Issue by mjstn** [UbiquityRobotics/demos#25]
We are likely going to need to have better up front avoidance.   This is discussed in issue 20 in demos repository for having any sort of object avoidance.

This issue here means a sonar board that has a few different set of holes so that it can be loaded in the normal way OR loaded to have the 'to the right' and 'to the left' sonars only point 30 deg off to each side or some other configuration.

This requires hacking current sensor placements and experiments to ensure colision can be avoided in assorted cases.    Perhaps we have center sonar then each side has a 35 deg and a 70 deg off to the side sonar.

I suggest we have a PC board where as a loading option we can load the right 45deg and left 45deg sensors in hole patterns that point off to the right and left about 30 degrees and they are on the right and left of the center sonar.   That way the electrical circuit is the same but we can choose a stronger center pattern.

We could also consider the two sensors that point direct to left and right also have alternate locations that each point mostly to the front but can see mostly forward and a little to sides.

Experiments with sonar avoidance will help us decide on the right angles to be using.

This change requires changes to the URDF file so user can select one or the other.   Perhaps the sonars should use robot.yaml setting to select WHICH sonar orientation is in use.  This would be much like we do now with raspicam poses of   'upward', 'forward' and 'downward' and so on.

**Comment by rohbotics** [comment]
Closing all floor follow related issues.
